USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_MEDIDAS AS
SELECT
    CONCAT (
        [medida_NUMERO_NOTA],
        '-',
        [medida_NUMERO_INTERNO_PARTE],
        '-',
        [medida_NUMERO_MEDIDA]
    ) AS NOTA_NR,
    nota_NOTA AS NOTA_ZR,
    nota_ORDEM AS ORDEM_ZR,
    medida_NUMERO_INTERNO_MEDIDA AS MEDIDA_NR_INT,
    nota_TIPO_NOTA AS NOTA_TIPO,
    CONCAT(
        'Med: ',
        [medida_TEXTO_BREVE_MEDIDA],
        ' ',
        [txt_longo_TELO_TX_LINHA]
    ) AS DESCRICAO,
    medida_DATA_CRIACAO AS DT_CRIACAO,
    medida_CODIGO_USUARIO_CRIACAO AS CRIADO_POR,
    CONCAT(
        [medida_CODIGO_PARCEIRO_RESPONSAVEL],
        '-',
        [medida_CODIGO_CENTRO_SAP_LOCALIZACAO]
    ) AS COD_RESP,
    nota_LOCAL_INSTALACAO AS LOC_INST,
	LEFT([nota_LOCAL_INSTALACAO], 6) AS COD_PLAT,
    SUBSTRING([nota_LOCAL_INSTALACAO], CHARINDEX('.', [nota_LOCAL_INSTALACAO]) + 1, 4) AS COD_SIST,
	CASE 
        WHEN CHARINDEX('SSUC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN '7 - SSUC'
        WHEN CHARINDEX('CANC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 OR CHARINDEX('ELIM', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN '6 - ELIMINADA'
        WHEN CHARINDEX('MSUC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN '5 - QUITADA/ENCERADA'
        WHEN CHARINDEX('MEDE', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN '4 - MEDE - AG. QUITAR/ENCERRAR'
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 AND medida_NUMERO_ORDEM_MANUNTECAO <> '' THEN '4 - ORDEM GERADA'
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 AND medida_NUMERO_ORDEM_MANUNTECAO = '' THEN '3 - TRIADA/GERAR ORDEM'
        WHEN CHARINDEX('INIT', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 OR CHARINDEX('CTEC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN '1 - RTI NOVA - AGUARD APROV PH'
        WHEN CHARINDEX('PH', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN '2 - APROV PH/AGUARD LIB DA OP'
        ELSE 'Verificar'
    END AS SIT_MEDIDA,
    nota_EQUIPAMENTO AS EQUIP,
    medida_CODIGO_CODE_MEDIDA AS CRIT_SELEC,
    medida_CODIGO_LOCALIZACAO AS LOCALIZACAO,
    medida_CODIGO_CATALOGO_MEDIDA AS PARADA_CAMPANHA,
    CONCAT (
        [medida_TEXTO_STATUS_SISTEMA],
        ' ',
        [medida_TEXTO_STATUS_USUARIO]
    ) AS STATUS,
    medida_CODIGO_PARCEIRO_RESPONSAVEL AS CT_DIRECIONADOR,
    CONCAT (
        [nota_STATUS_SISTEMA],
        ' ',
        [nota_STATUS_USUARIO]
    ) AS STATUS_ZR,
    medida_NUMERO_ORDEM_MANUNTECAO AS ORDEM,
    status_MSUC AS DT_MSUC,
    status_ELIM AS DT_ELIM,
    status_CANC AS DT_CANC,
    status_PH AS DT_PH,
    CASE
        WHEN medida_CODIGO_CODE_MEDIDA IS NULL THEN NULL
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%A%' THEN status_PH
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%B%' THEN DATEADD(DAY, 90, [status_PH])
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%C%' THEN DATEADD(DAY, 360, [status_PH])
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%D%' THEN DATEADD(DAY, 720, [status_PH])
        ELSE 'verificar'
    END AS DT_VENC,
    CASE
        WHEN CHARINDEX('CANC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0
        AND CHARINDEX('ELIM', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0
        AND CHARINDEX('MREL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0
        AND CHARINDEX('MSUC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0 THEN 1
        ELSE 0
    END AS PEND,
    CASE
        WHEN CHARINDEX('MSUC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MREL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0 THEN 1
        ELSE 0
    END AS QUIT,
    CASE
        WHEN CHARINDEX('CANC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('ELIM', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MREL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN 1
        ELSE 0
    END AS CANC,
    CASE
        WHEN status_MSUC IS NOT NULL THEN status_MSUC
        WHEN status_CANC IS NOT NULL THEN status_CANC
        WHEN status_ELIM IS NOT NULL THEN status_ELIM
        ELSE NULL
    END AS DT_ENCERRAMENTO,
    CASE
        WHEN CHARINDEX('CTEC', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0 THEN 1
        ELSE 0
    END AS QT_CTEC,
    CASE
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MEDL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('GAD', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0
        AND medida_NUMERO_ORDEM_MANUNTECAO IS NULL THEN 1
        ELSE 0
    END AS MED_AP,
    CASE
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MEDL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('GAD', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND medida_NUMERO_ORDEM_MANUNTECAO IS NULL THEN 1
        ELSE 0
    END AS TRI_SO,
    CASE
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MEDL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('GAD', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND medida_NUMERO_ORDEM_MANUNTECAO IS NOT NULL THEN 1
        ELSE 0
    END AS TRI_CO,
        CASE
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MEDL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0 THEN 1
        ELSE 0
    END AS INC1,
    CASE
        WHEN CHARINDEX('RECB', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('MEDL', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) > 0
        AND CHARINDEX('GAD', medida_TEXTO_STATUS_SISTEMA + ' ' + medida_TEXTO_STATUS_USUARIO) = 0
        AND medida_NUMERO_ORDEM_MANUNTECAO IS NULL THEN 1
        ELSE 0
    END AS INC2
FROM
    [BD_UNBCDIGITAL].[dbo].[GFM_VW_NOTA_MEDIDA_TXT]