USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_ORDENS AS
SELECT
	ORDEM,
	TIPO_ORDEM,
	GPM_ORDEM + ' ' + CENTRO_PLANEJAMENTO AS COD_RESP,
	TAM,
	STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM AS STATUS_ORDEM,
    LEFT(LOCAL_INSTALACAO, 6) AS COD_PLAT,
    SUBSTRING(LOCAL_INSTALACAO, CHARINDEX('.', LOCAL_INSTALACAO) + 1, 4) AS COD_SIST,
	CT_RESPONSAVEL AS CT_RESP_ORDEM,
    CENTRO_CT_RESPONSAVEL AS CENTRO,
    CASE 
        WHEN STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM = '' OR STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM IS NULL OR STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM = ' ' THEN '0 - Arquivamento SAP'
        WHEN CHARINDEX('ABER', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '1 - Ordem Aberta'
        WHEN CHARINDEX('LIB  CONF', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '4 - Ordem Conf.Final'
        WHEN CHARINDEX('LIB  CNPA', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '3 - Ordem Conf.Parcial'
        WHEN CHARINDEX('LIB', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '2 - Ordem Liberada'
        WHEN CHARINDEX('NEXE', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 OR 
                CHARINDEX('MREL', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 OR 
                CHARINDEX('EXCL', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 OR 
                CHARINDEX('SCAN', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 OR 
                CHARINDEX('ELIM', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '6 - Ordem Eliminada/ Não Executada'
        WHEN CHARINDEX('ENTE', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '5 - Ordem Encerrada tecnicamente'
        WHEN CHARINDEX('ENCE', STATUS_SISTEMA_ORDEM + ' ' + STATUS_USUARIO_ORDEM) > 0 THEN '6 - Ordem Comercialmente'
        ELSE 'Verificar'
    END AS SIT_ORDEM,
    DATA_BASE_FIM,
    DATA_BASE_INICIO,
    DATA_ENTE,
    DATA_ENCE,
    DATA_INICIO_REAL,
    DATA_FIM_REAL,
    DATA_HORA_ATUALIZACAO_STAGING AS ULTIMA_CARGA_STAGING,
    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM
	[BD_UNBCDIGITAL].[biin].[ordem_manutencao];