USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_OPERACAO AS
SELECT
	ORDEM,
	SEQUENCIA_CRIACAO_OPER,
	OPERACAO,
	SUB_OPERACAO,
	CT,
	CHAVE_CONTROLE,
	TEXTO_OPERACAO,
	EXECUTANTES,
	DURACAO,
	UNIDADE_DURACAO,
	STATUS_SISTEMA_OPERACAO,
	STATUS_USUARIO_OPERACAO,
	TRABALHO,
	TRABALHO_REAL,
	COD_RESTRICAO_INICIO,
	RESTRICAO_INICIO,
	COD_RESTRICAO_FIM,
	RESTRICAO_FIM,
	NUMERO_OBJETO_OPERACAO,
	CONFIRMACAO,
	QTDE_APROPRIACOES,
	DATA_INICIO,
	DATA_FIM,
	DATA_HORA_ATUALIZACAO_STAGING,
	DATA_HORA_ATUALIZACAO_ods
FROM
	[BD_UNBCDIGITAL].[biin].[operacao_manutencao];