USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_NOTAS AS
SELECT
    TOP 1000 
    NOTA AS NOTA_NR,
    TIPO_NOTA AS NOTA_TIPO,
    'Nota: ' + TEXTO_BREVE AS DESCRICAO,
    DATA_CRIACAO AS DT_CRIACAO,
    CHAVE_CRIADOR_NOTA AS CRIADO_POR,
    GPM_NOTA + '-' + CENTRO_PLANEJAMENTO AS COD_RESP,
    CT_RESPONSAVEL + '-' + CENTRO_PLANEJAMENTO AS COD_CT_RESP,
    LOCAL_INSTALACAO AS LOC_INST,
    EQUIPAMENTO AS EQUIP,
    CAMPO_SELECAO as CRIT_SELEC,
    STATUS_SISTEMA + ' ' + STATUS_USUARIO AS STATUS,
    DATA_ENCERRAMENTO,
    DATA_FIM_DESEJADO AS DT_VENC,
    LEFT(LOCAL_INSTALACAO, 6) AS COD_PLAT,
    SUBSTRING(LOCAL_INSTALACAO, CHARINDEX('.', LOCAL_INSTALACAO) + 1, 4) AS COD_SIST,
    CASE WHEN DATA_ENCERRAMENTO IS NULL THEN 1 ELSE 0 END AS PEND,
    CASE WHEN DATA_ENCERRAMENTO IS NOT NULL AND (STATUS_SISTEMA + ' ' + STATUS_USUARIO) NOT LIKE '%MREL%' THEN 1 ELSE 0 END AS QUIT,
    CASE WHEN DATA_ENCERRAMENTO IS NOT NULL AND (STATUS_SISTEMA + ' ' + STATUS_USUARIO) LIKE '%MREL%' THEN 1 ELSE 0 END AS CANC,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'IMED' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'PRIA' THEN 1 ELSE 0 END AS IMED_PRIA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'IMPD' THEN 1 ELSE 0 END AS IMPD,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'ABRA' THEN 1 ELSE 0 END AS ABRA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'SUSP' THEN 1 ELSE 0 END AS SUSP,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'TRIA' THEN 1 ELSE 0 END AS TRIA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'HABI' THEN 1 ELSE 0 END AS HABI,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'ARER' THEN 1 ELSE 0 END AS ARER,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'RANF' THEN 1 ELSE 0 END AS RANF,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'AAIN' THEN 1 ELSE 0 END AS AAIN,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'AANP' THEN 1 ELSE 0 END AS AANP,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'AANV' THEN 1 ELSE 0 END AS AANV,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'ACLA' THEN 1 ELSE 0 END AS ACLA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'AIBA' THEN 1 ELSE 0 END AS AIBA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'AMAR' THEN 1 ELSE 0 END AS AMAR,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'DLDX' THEN 1 ELSE 0 END AS DLDX,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'COI' THEN 1 ELSE 0 END AS COI,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'RTA' THEN 1 ELSE 0 END AS RTA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'VAZA' THEN 1 ELSE 0 END AS VAZA,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'NR10' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'EXNC' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'IEEX' THEN 1 ELSE 0 END AS EX_NR10,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'DRQC' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'DRQJ' THEN 1 ELSE 0 END AS DROPS,
    CASE WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'LUCA' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'LUPA' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'PPRO' OR STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'SUMS' THEN 1 ELSE 0 END AS PARADA_UMS,
    CASE 
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'CNTN' THEN 'Contingenciamento Não Necessário'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'CONT' THEN 'Contingenciado/Análise Cont'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'CNTS' THEN 'Contingenciamento Necessário'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'CNTA' THEN 'Avaliar Nec. Contingenciamento'
    ELSE NULL 
    END AS CONTINGENCIAMENTO,
    CASE 
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'CRIT' THEN 'Classe Crítica de NC'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'GRAV' THEN 'Classe Grave de NC'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'MODE' THEN 'Classe Moderada de NC'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'LEVE' THEN 'Classe Leve de NC'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'MGRA' THEN 'NC Ex de categoria Muito Grave'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'MLEV' THEN 'NC Ex de categoria Muito Leve'
    ELSE NULL
    END AS CRITICIDADE_CLASSE,
    CASE 
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'GRGI' THEN 'Grades piso-RGI Risco grave'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'PPIA' THEN 'Plano pintura - Alta'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'GALT' THEN 'Grades piso-Risco alto'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'GMOD' THEN 'Grades piso-Risco moderado'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'PPIM' THEN 'Plano pintura - Média'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'GBAI' THEN 'Grades piso-Risco baixo'
        WHEN STATUS_SISTEMA + ' ' + STATUS_USUARIO = 'PPIB' THEN 'Plano pintura - Baixa'
    ELSE NULL 
    END AS CRITICIDADE_GRADE_PINTURA,
    DATA_HORA_ATUALIZACAO_STAGING AS ULTIMA_CARGA_STAGING,
    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM
    [BD_UNBCDIGITAL].[biin].[nota_manutencao]
WHERE
    TIPO_NOTA <> 'ZR';