USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_NOTAS AS
SELECT
    NOTA AS NOTA_NR,
    TIPO_NOTA AS NOTA_TIPO,
    'Nota: ' + TEXTO_BREVE AS DESCRICAO,
    DATA_CRIACAO AS DT_CRIACAO,
    CHAVE_CRIADOR_NOTA AS CRIADO_POR,
    GPM_NOTA + '-' + CENTRO_PLANEJAMENTO AS COD_RESP,
    CT_RESPONSAVEL + '-' + CENTRO_PLANEJAMENTO AS COD_CT_RESP,
    LOCAL_INSTALACAO AS LOC_INST,
	LEFT(LOCAL_INSTALACAO, 6) AS COD_PLAT,
    SUBSTRING(LOCAL_INSTALACAO, CHARINDEX('.', LOCAL_INSTALACAO) + 1, 4) AS COD_SIST,
    EQUIPAMENTO AS EQUIP,
    CAMPO_SELECAO as CRIT_SELEC,
    STATUS_SISTEMA + ' ' + STATUS_USUARIO AS STATUS,
    DATA_ENCERRAMENTO AS DATA_ENC,
    DATA_FIM_DESEJADO AS DT_VENC,
    CASE 
        WHEN CHARINDEX('MREL', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '6 - ELIMINADA'
        WHEN CHARINDEX('MSEN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '5 - QUITADA/ENCERRADA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 AND ORDEM IS NOT NULL THEN '4 - ORDEM GERADA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 AND CHARINDEX('TRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) = 0 THEN '1 - AVALIAR/TRIAR NOTA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 AND CHARINDEX('SUSP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '2 - SUSPENSA'
        WHEN CHARINDEX('MSPR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '3 - TRIADA/GERAR ORDEM'
        WHEN CHARINDEX('MSPN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 OR CHARINDEX('MSDI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN '0 - AGUARD.LIB/APROV'
        ELSE 'VERIFICAR'
    END AS SIT_NOTAS,
    CASE WHEN DATA_ENCERRAMENTO IS NULL THEN 1 ELSE 0 END AS PEND,
    CASE WHEN DATA_ENCERRAMENTO IS NOT NULL AND (STATUS_SISTEMA + ' ' + STATUS_USUARIO) NOT LIKE '%MREL%' THEN 1 ELSE 0 END AS QUIT,
    CASE WHEN DATA_ENCERRAMENTO IS NOT NULL AND (STATUS_SISTEMA + ' ' + STATUS_USUARIO) LIKE '%MREL%' THEN 1 ELSE 0 END AS CANC,
    CASE WHEN CHARINDEX('IMED', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 OR CHARINDEX('PRIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS IMED_PRIA,
    CASE WHEN CHARINDEX('IMPD', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS IMPD,
    CASE WHEN CHARINDEX('ABRA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS ABRA,
    CASE WHEN CHARINDEX('HABI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS HABI,
    CASE WHEN CHARINDEX('ARER', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS ARER,
    CASE WHEN CHARINDEX('RANF', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS RANF,
    CASE WHEN CHARINDEX('AAIN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS AAIN,
    CASE WHEN CHARINDEX('AANP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS AANP,
    CASE WHEN CHARINDEX('AANV', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS AANV,
    CASE WHEN CHARINDEX('ACLA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS ACLA,
    CASE WHEN CHARINDEX('AIBA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS AIBA,
    CASE WHEN CHARINDEX('AMAR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS AMAR,
    CASE WHEN CHARINDEX('DLDX', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS DLDX,
    CASE WHEN CHARINDEX('COI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS COI,
    CASE WHEN CHARINDEX('RTA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS RTA,
    CASE WHEN CHARINDEX('VAZA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VAZA,
    CASE WHEN CHARINDEX('EXOP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS EXOP,
    CASE
        WHEN CHARINDEX('NR10', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
        OR CHARINDEX('EXNC', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
        OR CHARINDEX('IEEX', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1
        ELSE 0
    END AS EX_NR10,
    CASE
        WHEN CHARINDEX('DRQC', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
        OR CHARINDEX('DRQJ', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1
        ELSE 0
    END AS DROPS,
    CONCAT(
        CAST(CASE WHEN CHARINDEX('ABRA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('HABI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('ARER', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('RANF', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('AAIN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('AANP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('AANV', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('ACLA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('AIBA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('AMAR', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('DLDX', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('COI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('RTA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('VAZA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE WHEN CHARINDEX('EXOP', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1 ELSE 0 END AS VARCHAR(1)),
        CAST(CASE 
            WHEN CHARINDEX('NR10', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
            OR CHARINDEX('EXNC', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 
            OR CHARINDEX('IEEX', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1
            ELSE 0
        END AS VARCHAR(1)),
        CAST(CASE
            WHEN CHARINDEX('DRQC', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
            OR CHARINDEX('DRQJ', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1
            ELSE 0
        END AS VARCHAR(1))
    ) AS CONCAT_COLS,
    CASE
        WHEN CHARINDEX('LUCA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
        OR CHARINDEX('LUPA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
        OR CHARINDEX('PPRO', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0
        OR CHARINDEX('SUMS', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 1
        ELSE 0
    END AS PARADA_UMS,
     CASE 
        WHEN CHARINDEX('CNTN', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Contingenciamento Não Necessário'
        WHEN CHARINDEX('CONT', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Contingenciado/Análise Cont'
        WHEN CHARINDEX('CNTS', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Contingenciamento Necessário'
        WHEN CHARINDEX('CNTA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Avaliar Nec. Contingenciamento'
    ELSE NULL 
    END AS CONTINGENCIAMENTO,
    CASE 
        WHEN CHARINDEX('CRIT', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Classe Crítica de NC'
        WHEN CHARINDEX('GRAV', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Classe Grave de NC'
        WHEN CHARINDEX('MODE', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Classe Moderada de NC'
        WHEN CHARINDEX('LEVE', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Classe Leve de NC'
        WHEN CHARINDEX('MGRA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'NC Ex de categoria Muito Grave'
        WHEN CHARINDEX('MLEV', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'NC Ex de categoria Muito Leve'
    ELSE NULL
    END AS CRITICIDADE_CLASSE,
    CASE 
        WHEN CHARINDEX('GRGI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Grades piso-RGI Risco grave'
        WHEN CHARINDEX('PPIA', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Plano pintura - Alta'
        WHEN CHARINDEX('GALT', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Grades piso-Risco alto'
        WHEN CHARINDEX('GMOD', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Grades piso-Risco moderado'
        WHEN CHARINDEX('PPIM', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Plano pintura - Média'
        WHEN CHARINDEX('GBAI', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Grades piso-Risco baixo'
        WHEN CHARINDEX('PPIB', STATUS_SISTEMA + ' ' + STATUS_USUARIO) > 0 THEN 'Plano pintura - Baixa'
    ELSE NULL 
    END AS CRITICIDADE_GRADE_PINTURA,
    DATA_HORA_ATUALIZACAO_STAGING AS ULTIMA_CARGA_STAGING,
    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM
    BD_UNBCDIGITAL.biin.nota_manutencao
WHERE
    TIPO_NOTA <> 'ZR';
