USE [BD_UNBCDIGITAL]
GO

CREATE TABLE [dbo].[GFM_HISTORICO_STATUS_NOTA] (
    OBJETO NVARCHAR(255),
    STATUS_OBJETO NVARCHAR(255),
    MODIFICACAO NVARCHAR(255),
    TIPO_STATUS NVARCHAR(255),
    TEXTO_BREVE_STATUS NVARCHAR(255),
    TEXTO_COMPLETO_STATUS NVARCHAR(MAX),
    USUARIO_MODIFICACAO NVARCHAR(255),
    DATA_MODIFICACAO DATETIME,
    CODIGO_TRANSACAO_SAP NVARCHAR(255),
    INDICADOR_STATUS_INATIVO BIT,
    INDICADOR_TIPO_MODIFICACAO NVARCHAR(255),
    TIPO_OBJETO_TEXTO_LONGO NVARCHAR(MAX),
    DATA_HORA_ATUALIZACAO_STAGING DATETIME,
    DATA_HORA_ATUALIZACAO_ODS DATETIME
);
