USE [BD_UNBCDIGITAL]
GO

CREATE VIEW GFM_VW_ORDENS AS
SELECT
	ORDEM,
	TIPO_ORDEM,
	CONCAT(GPM_ORDEM, ' ', CENTRO_PLANEJAMENTO) AS COD_RESP,
	TAM,
	CONCAT(STATUS_SISTEMA_ORDEM, ' ', STATUS_USUARIO_ORDEM) AS STATUS_ORDEM,
    LEFT(LOCAL_INSTALACAO, 6) AS COD_PLAT,
    SUBSTRING(LOCAL_INSTALACAO, CHARINDEX('.', LOCAL_INSTALACAO) + 1, 4) AS COD_SIST,
	CT_RESPONSAVEL AS CT_RESP_ORDEM,
    CENTRO_CT_RESPONSAVEL AS CENTRO,
    DATA_BASE_FIM,
    DATA_BASE_INICIO,
    DATA_ENTE,
    DATA_ENCE,
    DATA_INICIO_REAL,
    DATA_FIM_REAL,
    DATA_HORA_ATUALIZACAO_STAGING AS ULTIMA_CARGA_STAGING,
    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM
	[BD_UNBCDIGITAL].[biin].[ordem_manutencao];