CREATE VIEW GFM_VW_NOTAS AS
SELECT
    NOTA AS NOTA_NR,
    TIPO_NOTA AS NOTA_TIPO,
    CONCAT('Nota: ', TEXTO_BREVE) AS DESCRICAO,
    DATA_CRIACAO AS DT_CRIACAO,
    CHAVE_CRIADOR_NOTA AS CRIADO_POR,
    GPM_NOTA || '-' || CENTRO_PLANEJAMENTO AS COD_RESP,
    CT_RESPONSAVEL || '-' || CENTRO_PLANEJAMENTO AS COD_CT_RESP,
    LOCAL_INSTALACAO AS LOC_INST,
    EQUIPAMENTO AS EQUIP,
    CAMPO_SELECAO as CRIT_SELEC,
    STATUS_SISTEMA || ' ' || STATUS_USUARIO AS STATUS,
    DATA_ENCERRAMENTO,
    DATA_FIM_DESEJADO AS DT_VENC,
    LEFT(LOCAL_INSTALACAO, 6) AS COD_PLAT,
    CASE
        WHEN DATA_ENCERRAMENTO IS NULL THEN 1
        ELSE 0
    END AS PEND,
    CASE
        WHEN DATA_ENCERRAMENTO IS NOT NULL
        AND (STATUS_SISTEMA || ' ' || STATUS_USUARIO) NOT LIKE '%MREL%' THEN 1
        ELSE 0
    END AS QUIT,
    CASE
        WHEN DATA_ENCERRAMENTO IS NOT NULL
        AND (STATUS_SISTEMA || ' ' || STATUS_USUARIO) LIKE '%MREL%' THEN 1
        ELSE 0
    END AS CANC,
    DATA_HORA_ATUALIZACAO_STAGING AS ULTIMA_CARGA_STAGING,
    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM
    BIIN.BIIN.VW_NOTA_MANUTENCAO;
