CREATE VIEW GFM_VW_MEDIDAS AS
SELECT
    medida_NUMERO_NOTA || '-' || medida_NUMERO_INTERNO_PARTE || '-' medida_NUMERO_MEDIDA AS NOTA_NR,
    nota_NOTA AS NOTA_ZR,
    nota_ORDEM AS ORDEM_ZR,
    medida_NUMERO_INTERNO_MEDIDA AS MEDIDA_NR_INT,
    nota_TIPO_NOTA AS NOTA_TIPO,
    'Med: ' || medida_TEXTO_BREVE_MEDIDA || ' ' || txt_longo_TELO_TX_LINHA AS DESCRICAO,
    medida_DATA_CRIACAO AS DT_CRIACAO,
    medida_CODIGO_USUARIO_CRIACAO AS CRIADO_POR,
    medida_CODIGO_PARCEIRO_RESPONSAVEL || '-' || medida_CODIGO_CENTRO_SAP_LOCALIZACAO AS COD_RESP,
    nota_LOCAL_INSTALACAO AS LOC_INST,
    nota_EQUIPAMENTO AS EQUIP,
    medida_CODIGO_CODE_MEDIDA AS CRIT_SELEC,
    medida_CODIGO_LOCALIZACAO AS LOCALIZACAO,
    medida_CODIGO_CATALOGO_MEDIDA AS PARADA_CAMPANHA,
    medida_TEXTO_STATUS_SISTEMA || ' ' || medida_TEXTO_STATUS_USUARIO AS STATUS,
    medida_CODIGO_PARCEIRO_RESPONSAVEL AS CT_DIRECIONADOR,
    nota_STATUS_SISTEMA || ' ' || nota_STATUS_USUARIO AS STATUS_ZR,
    medida_NUMERO_ORDEM_MANUNTECAO AS ORDEM,
    status_MSUC AS DT_MSUC,
    status_ELIM AS DT_ELIM,
    status_CANC AS DT_CANC,
    status_PH AS DT_PH,
    CASE
        WHEN medida_CODIGO_CODE_MEDIDA IS NULL THEN NULL
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%A%' THEN status_PH
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%B%' THEN 
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%C%' THEN 
        WHEN medida_CODIGO_CODE_MEDIDA LIKE '%D%' THEN 
FROM
    BIIN.BIIN.VW_NOTA_MEDIDA_TXT
