CREATE VIEW GFM_VW_ORDENS AS
SELECT
    ORDEM,
    TIPO_ORDEM,
    TEXTO_BREVE,
    GPM_ORDEM || '-' || CENTRO_PLANEJAMENTO AS COD_RESP,
    TAM,
    STATUS_SISTEMA_ORDEM || ' ' || STATUS_USUARIO_ORDEM AS STATUS_ORDEM,
    CT_RESPONSAVEL AS CT_RESP_ORDEM,
    CENTRO_CT_RESPONSAVEL AS CENTRO,
    DATA_BASE_FIM,
    DATA_BASE_INICIO,
    DATA_ENTE,
    DATA_ENCE,
    DATA_INICIO_REAL,
    DATA_FIM_REAL,
    DATA_HORA_ATUALIZACAO_STAGING AS ULTIMA_CARGA_STAGING,
    DATA_HORA_ATUALIZACAO_ODS AS ULTIMA_CARGA_ODS
FROM
    BIIN.BIIN.VW_ORDEM_MANUTENCAO;
